[supervisord]
nodaemon=true
loglevel=info
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:app-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work --sleep=2 --tries=1 --timeout=80
autostart=true
autorestart=true
numprocs=1
stdout_logfile=/var/log/app_worker.log
stderr_logfile=/var/log/app_worker.err

[program:app-server]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan serve --host=0.0.0.0
autostart=true
autorestart=true
numprocs=1
stdout_logfile=/var/log/app_server.log
stderr_logfile=/var/log/app_server.err

[program:app-vite]
process_name=%(program_name)s_%(process_num)02d
command=npm run dev --prefix /var/www
autostart=true
autorestart=true
numprocs=1
stdout_logfile=/var/log/app_vite.log
stderr_logfile=/var/log/app_vite.err
