services:
  frontend:
    build:
      dockerfile: docker/frontend/Dockerfile
      context: .
    ports:
      - '80:80'

  backend:
    build:
      dockerfile: docker/backend/Dockerfile
      context: .
    ports:
      - '81:8080'

  postgres:
    image: postgres:17-alpine
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
      - POSTGRES_DB=finance

volumes:
  db:
