version: '3.8'

services:
  frontend:
    image: node:23-alpine
    volumes:
      - ./frontend:/app/frontend
    command:
      - yarn
      - dev
    working_dir: /app/frontend
    ports:
      - '3000:5173'
