services:
  frontend:
    image: node:23-alpine
    volumes:
      - ./:/app
    command: sh -c 'yarn install && yarn dev'
    working_dir: /app
    ports:
      - '3000:5173'

  postgres:
    image: postgres:17-alpine
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5600:5432'
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
      - POSTGRES_DB=finance

volumes:
  db:
