logger:
  level: debug
  encoding: json
  enable_caller: true
  sampling:
    initial: 100
    thereafter: 100

database:
  debug: false

auth:
  access_secret_key:
  refresh_secret_key:

frontend:
  base_url:
