logger:
  encoding: console

database:
  dsn: postgres://user:user@localhost:5600/finance?sslmode=disable
  debug: true

auth:
  access_secret_key: KNeEmRLEjF65YhWjMz64
  refresh_secret_key: pBCCOYZaXdwvpy7pg553

frontend:
  base_url: http://localhost:3000
