logger:
  encoding: console

database:
  dsn: postgresql://user:user@postgres/finance?sslmode=disable
  debug: true

auth:
  access_secret_key: KNeEmRLejF65YhWjMz64
  refresh_secret_key: pBCCOYZAXdwvpy7pg553

frontend:
  base_url: http://212.193.61.50
