name: Checks

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install dependencies
        run: |
          cd frontend
          yarn install

      - name: Run ESLint
        run: |
          cd frontend
          yarn lint

  typescript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install dependencies
        run: |
          cd frontend
          yarn install

      - name: Run TypeScript check
        run: |
          cd frontend
          yarn tsc -b

  golang:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.3

      - name: Install dependencies
        run: go mod download

      - name: Check formatting
        run: gofmt -l .

      - name: Verify dependencies
        run: go mod tidy && git diff --exit-code

      - name: Run vulnerability check
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...

      - name: Build
        run: go build ./...
